// maps/buttonMap.js
module.exports = {
  // MATCHES
  'match_pick:': 'openMatchPick',
  'open_results_matches': 'openMatchResults',
  'clear_user_picks': 'clearDatabaseHandler',
  'full_reset': 'clearDatabaseHandler',
  'clear_only_results_confirm': 'clearDatabaseHandler',
  'calculate_scores': 'calculateScores',
  'export_ranking': 'exportClassification',
  'export_full_summary': 'buttonExportFullSummary',
  'submit_playin_results': 'setPlayinResults',
  'clear_db_yes': 'clearDatabaseHandler',
  'clear_db_no': 'clearDatabaseHandler',
  'clear_all_yes': 'clearDatabaseHandler',
  'clear_all_no': 'clearDatabaseHandler',
  'clear_only_results_yes': 'clearDatabaseHandler',
  'clear_only_results_no': 'clearDatabaseHandler',
  'clear_db_confirm': 'clearDatabaseHandler',
  'clear_db_with_results': 'clearDatabaseHandler',
  'backup_database': 'backupDatabase',
  'restore_backup': 'restoreBackupButton',
  'start_swiss_stage_1': 'openSwissDropdown',
  'start_swiss_stage_2': 'openSwissDropdown',
  'start_swiss_stage_3': 'openSwissDropdown',
  'submit_swiss_stage1': 'submitSwissDropdown',
  'submit_swiss_stage2': 'submitSwissDropdown',
  'submit_swiss_stage3': 'submitSwissDropdown',
  'set_results_swiss_stage1': 'openSwissResultsDropdown',
  'set_results_swiss_stage2': 'openSwissResultsDropdown',
  'set_results_swiss_stage3': 'openSwissResultsDropdown',
  'confirm_playoffs': 'submitPlayoffsDropdown',
  'open_playoffs_dropdown': 'openPlayoffsDropdown',
  'open_results_playoffs': 'openPlayoffsResultsDropdown',
  'confirm_playoffs_results': 'submitPlayoffsResultsDropdown',
  'set_results_double': 'openDoubleElimResultsDropdown',
  'confirm_doubleelim': 'submitDoubleElimDropdown',
  'open_playin_dropdown': 'openPlayinDropdown',
  'confirm_playin': 'submitPlayinDropdown',
  'set_results_playin': 'openPlayinResultsDropdown',
  'confirm_playin_results': 'submitPlayinResultsDropdown',
  'start_stage1': 'openSwissDropdown',
  'start_stage2': 'openSwissDropdown',
  'start_stage3': 'openSwissDropdown',
  'ranking_prev': 'rankingPagination',
  'ranking_next': 'rankingPagination',
  'confirm_stage1': 'submitSwissDropdown',
  'confirm_stage2': 'submitSwissDropdown',
  'confirm_stage3': 'submitSwissDropdown',
  'confirm_official_doubleelim': 'submitDoubleElimResultsDropdown',
  'open_restore_dropdown': 'openRestoreDropdown',
  'confirm_restore_backup': 'confirmRestoreBackup',
  'cancel_restore_backup': 'confirmRestoreBackup',
  'add_match': 'openAddMatch',
  'clear_matches': 'openClearMatches',
  'match_add_cancel': 'matchAddCancel',
  'match_add_again': 'matchAddAgain',
  'match_admin_exact_open': 'matchAdminExactOpen',
  'match_user_exact_open': 'matchUserExactOpen',
  'match_admin_exact_open_next': 'matchAdminExactOpenNext',
  'match_user_exact_open_next': 'matchUserExactOpenNext',
  'match_exact_open': 'matchUserExactOpen',
  'open_doubleelim_modal': 'openDoubleElimDropdown',



    // ===== ADMIN PANEL (UPROSZCZONY) =====
  'panel:open:results': 'panelOpenMenu',
  'panel:open:matches': 'panelOpenMenu',
  'panel:open:db': 'panelOpenMenu',
  'panel:open:danger': 'panelOpenMenu',
  'panel:danger:cancel': 'panelDangerCancel',
  'panel:open:teams': 'openTeamsManager',
  'match_admin_start_open:': 'matchAdminStartOpen',
  'match_admin_lock_toggle:': 'matchAdminLockToggle',

   // ===== TEAMS MANAGER =====
  'teams:refresh': 'openTeamsManager',
  'teams:page_prev': 'teamsPageNav',
  'teams:page_next': 'teamsPageNav',
  'teams:add': 'teamsAddOpen',
  'teams:rename': 'teamsRenameOpen',
  'teams:toggle': 'teamsToggle',
  'teams:delete': 'teamsDeleteConfirmOpen',
  'teams:delete_yes': 'teamsDeleteConfirm',
  'teams:delete_no': 'openTeamsManager',
  'teams:export': 'teamsExport',
  'teams:import': 'teamsImportOpen',
  'teams:seed_from_file': 'teamsSeedFromFile',

  'match_admin_start_open:': 'matchAdminStartOpen',
  'match_admin_lock_toggle:': 'matchAdminLockToggle'

  




};
